"""empty message

Revision ID: c1772315c711
Revises: bc5f5cdc67cd
Create Date: 2019-04-24 14:59:55.421863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1772315c711'
down_revision = 'bc5f5cdc67cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_song_location', table_name='song')
    op.create_index(op.f('ix_song_location'), 'song', ['location'], unique=True)
    op.drop_index('ix_song_name', table_name='song')
    op.create_index(op.f('ix_song_name'), 'song', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_name'), table_name='song')
    op.create_index('ix_song_name', 'song', ['name'], unique=False)
    op.drop_index(op.f('ix_song_location'), table_name='song')
    op.create_index('ix_song_location', 'song', ['location'], unique=False)
    # ### end Alembic commands ###
